services:
  db-mysql:
    container_name: mysql-finances
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: joao
      MYSQL_DATABASE: finances
    ports:
      - "3307:3306"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-finances
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456