server:
  port: 80

spring:
  application:
    name: finances

  datasource:
    url: jdbc:postgresql://ec2-54-158-26-89.compute-1.amazonaws.com:5432/de31lhss3cultl
    username: hpsyvogsqbztvk
    password: a6749e009a1180146ca374e2a884690fa59b7f5535e61de9b5c63dd2f70a1221
  # variavel de ambiente do heroku, que providencia um banco padrão


  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    tls: true
    username: facildespesa@gmail.com
    password: D3spes@Fac1l
    test-connection: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

#  mail:
#    host: smtp.mailtrap.io
#    port: 2525
#    username: 746a4ee534b529
#    password: 7af5faeee6d2b9
#    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz