server:
  port: 8090

spring:

  application:
    name: finances

  datasource:
    url: jdbc:mysql://localhost:3306/finances
    username: root
    password: joaoflavio

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d02c5b57a35423
    password: 9117bf7177395f
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz