server:
  port: 8090

spring:

  application:
    name: finances

  rabbitmq:
    addresses: amqps://zpqvtjak:AXMkh2gOZtNpOZmoWMN-Nq6eOdJCBUhL@chimpanzee.rmq.cloudamqp.com/zpqvtjak
    host: localhost
    port: 5672
    username: admin
    password: 123456

  datasource:
    url: jdbc:mysql://localhost:3307/finances
    username: root
    password: joao

  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 9a75971236d92c
    password: a76e0329cbf718
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz