
spring:
  application:
    name: finances

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d02c5b57a35423
    password: 9117bf7177395f
    test-connection: true

security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz