
spring:
  application:
    name: finances

  port: 8090

  mail:
    host: smtp.mailtrap.io
    port: 25
    username: d02c5b57a35423
    password: 9117bf7177395f
    ssl: false
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz