server:
  port: 8090

spring:

  application:
    name: finances

  rabbitmq:
    addresses: amqps://ddssohmz:UkTPfpcEB5KvqE_bu37s2nb2-yoNQ8ru@shark.rmq.cloudamqp.com/ddssohmz
    host: localhost
    port: 5672
    username: admin
    password: 123456

  datasource:
    url: jdbc:mysql://localhost:3307/finances
    username: root
    password: joao

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: d02c5b57a35423
    password: 9117bf7177395f
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz