server:
  port: 80

spring:
  application:
    name: finances

  rabbitmq:
    addresses: amqps://ddssohmz:UkTPfpcEB5KvqE_bu37s2nb2-yoNQ8ru@shark.rmq.cloudamqp.com/ddssohmz
    host: localhost
    port: 5672
    username: admin
    password: 123456

  datasource:
    url: jdbc:postgresql://ec2-54-158-26-89.compute-1.amazonaws.com:5432/de31lhss3cultl
    username: hpsyvogsqbztvk
    password: a6749e009a1180146ca374e2a884690fa59b7f5535e61de9b5c63dd2f70a1221


  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect


  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 746a4ee534b529
    password: 7af5faeee6d2b9
    test-connection: true


security:
  jwt:
    token:
      expire-in:  86400000
      secret-key: c2VjcmV0LWZpbmFuY2Vz